---
 #Anything between <angle brackets> has to be filled-in before use.
- name: GET AND CONFIGURE PYTHON
  hosts: all
  remote_user: <username>
  become: yes
  tasks:
  - name: (...)

- name: PREPARE THE OS
  hosts: all
  remote_user: <username>
  become: yes
  tasks:
  - name: Upgrade already installed packages
    ansible.builtin.dnf:
      name: "*"
      state: latest
  
  - name: Install SELinux Policy tools
    ansible.builtin.dnf:
      name:
        - policycoreutils-python-utils
        - setools-console
      state: latest
  
  - name: Install Logwatch
    ansible.builtin.dnf:
      name: logwatch
      state: latest
  
  - name: Ensure systemd journal contents are retained
    ansible.builtin.file:
      path: /var/log/journal
      state: directory
      mode: '0700'
  
  - name: Move the primary network interface to the proper zone
    ansible.posix.firewalld:
      zone: drop
      interface: <eth0>
      state: enabled
      permanent: yes
      immediate: yes
  
  - name: Add rich rules to the secondary zone
    ansible.posix.firewalld:
      zone: block
      state: enabled
      permanent: yes
      immediate: yes
      rich_rule:
        - rule family=ipv4 source address=<ipv4 address (Hyper-V host)>/<mask> service name=postgresql accept
        - rule family=ipv4 source address=<ipv4 address (Linux Guest 1)>/<mask> service name=ssh accept
   
  - name: Move the secondary network interface to the proper zone
    ansible.posix.firewalld:
      zone: block
      interface: <eth1>
      state: enabled
      permanent: yes
      immediate: yes
  
  - name: Disable zone drifting
    ansible.builtin.lineinfile:
      path: /etc/firewalld/firewalld.conf
      line: AllowZoneDrifting=no
      regexp: '^AllowZoneDrifting='
  
  - name: Disable IPv6 on the secondary interface
    ansible.builtin.command: nmcli connection modify <eth1> ipv6.method disabled

- name: CONFIGURE POSTGRESQL REPOSITORIES
  hosts: all
  remote_user: <username>
  become: yes
  tasks:
  - name: Install the repository RPM
    ansible.builtin.command: dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
  
  - name: Disable the built-in PostgreSQL module
    ansible.builtin.command: dnf -qy module disable postgresql
...
