---
 #Anything between <angle brackets> has to be filled-in before use.

- name: Prepare the OS
  hosts: all #for now
  remote_user: <username>
  
  tasks:
  - name: Upgrade already installed packages
    ansible.builtin.dnf:
      name: "*"
      state: latest
  
  - name: Install SELinux Policy tools
    ansible.builtin.dnf:
      name:
        - policycoreutils-python-utils
        - setools-console
      state: latest
  
  - name: Install Logwatch
    ansible.builtin.dnf:
      name: logwatch
      state: latest
  
  - name: Ensure systemd journal contents are retained
    ansible.builtin.file:
      path: /var/log/journal
      state: directory
      mode: '0700'
  
  - name: Move the first network interface to the proper zone
    ansible.posix.firewalld:
      zone: drop
      interface: <eth0>
      permanent: yes
      state: enabled
      immediate: yes
      
...
